### ISSUE TITLE
how to delete multiple Row

### ISSUE THREAD

**Issue by thainguyenit** [paramquery/grid#130]
Hi,
Please help me, how to delete multiple Row?
My code is issue:

var $grid = $("#abc").pqGrid(obj);
function deleteRow() {
                var arrRowIndxs = $grid.pqGrid("selection", { type: 'row', method: 'getSelection' });
                if (arrRowIndxs.length != 0) {  
                    for (var i = 0; i < arrRowIndxs.length; i++) {
                        $grid.pqGrid("deleteRow", { rowIndx: arrRowIndxs[i], track: false });
                    }
                } else {
                    alert("No Records to delete");
                }

            }

Thank you

**Comment by lechurn** [comment]
what is the issue that you're facing with your code? it is possible delete multiple rows 
instead of passing rowIndx, you can pass rowIndx in an array.

> var $grid = $("#abc").pqGrid(obj);
function deleteRow() {
var arrRowIndxs = $grid.pqGrid("selection", { type: 'row', method: 'getSelection' });
if (arrRowIndxs.length != 0) {
for (var i = 0; i < arrRowIndxs.length; i++) {
$grid.pqGrid("deleteRow", { rowIndx: _**arrRowIndxs[i].rowData.rowIndx**_, track: false });
}
} else {
alert("No Records to delete");
}
}

> `
You refer to the example here:
https://paramquery.com/pro/api#method-deleteRow

the code above is my assumption only. feel free to correct me if i'm wrong.

**Comment by paramquery** [comment]
Multiple rows can be deleted at once with deleteRow method

https://paramquery.com/api#method-deleteRow
